"""allow completed events to release venue

Revision ID: 95b54549a51a
Revises: 7c7bf3ebec9d
Create Date: 2026-10-07 19:47:52.389695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b54549a51a'
down_revision: Union[str, Sequence[str], None] = '7c7bf3ebec9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'venue_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_events_venue'), 'events', type_='foreignkey')
    op.create_foreign_key(
    'fk_events_venue',
    'events',
    'venues',
    ['venue_id'],
    ['id'],
    ondelete='SET NULL'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_events_venue', 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_venue'), 'events', 'venues', ['venue_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('events', 'venue_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
