"""restrict venue deletion for active events

Revision ID: df80174f25be
Revises: 95b54549a51a
Create Date: 2026-10-07 19:59:23.991948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df80174f25be'
down_revision: Union[str, Sequence[str], None] = '95b54549a51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_events_venue'), 'events', type_='foreignkey')
    op.create_foreign_key('fk_events_venue', 'events', 'venues', ['venue_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_events_venue', 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_venue'), 'events', 'venues', ['venue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
