import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Layout from '../components/Layout'
import { useAuthContext } from '../context/AuthContext'
import { apiFetch } from '../services/api'

export default function Dashboard(){const{user,isEventManager}=useAuthContext();const[events,setEvents]=useState([]);const[regs,setRegs]=useState([]);const[summary,setSummary]=useState(null);const[error,setError]=useState('');useEffect(()=>{Promise.all([
  apiFetch('/events'),
  apiFetch(`/registrations/me?user_id=${user.id}`)
]).then(([e,r])=>{setEvents(e);setRegs(r)}).catch(e=>setError(e.message));if(isEventManager)apiFetch('/manager/summary').then(setSummary).catch(()=>{})},[isEventManager]);const upcoming=useMemo(()=>events.filter(e=>new Date(e.start_time)>new Date()&&e.status==='scheduled'),[events]);const regEventIds=new Set(regs.filter(r=>r.status!=='cancelled').map(r=>r.event_id));return <Layout><main className="page-container"><div className="page-heading"><div><span className="eyebrow">YOUR EVENT WORLD AT A GLANCE</span><h1>Good to see you, {user?.name?.split(' ')[0]}! 👋</h1><p>{isEventManager?'Manage events, registrations and revenue from real project data.':'Your events, venues and registrations — all in one place.'}</p></div></div>{error&&<div className="form-error">{error}</div>}<section className="stat-grid">{isEventManager?<><Stat label="Total Events" value={summary?.total_events??'—'} icon="◫"/><Stat label="Registrations" value={summary?.total_registrations??'—'} icon="◎"/><Stat label="Total Revenue" value={summary?`₹${Number(summary.total_revenue).toLocaleString('en-IN')}`:'—'} icon="₹"/><Stat label="Pending Payments" value={summary?.pending_payments??'—'} icon="◷"/></>:<><Stat label="Upcoming Events" value={upcoming.length} icon="◫"/><Stat label="My Registrations" value={regs.filter(r=>r.status!=='cancelled').length} icon="◎"/><Stat label="Available Events" value={events.filter(e=>e.status==='scheduled').length} icon="✦"/><Stat label="Saved Venues" value="Explore" icon="⌖"/></>}</section><section className="dashboard-grid"><div className="panel"><div className="panel-head"><h2>Upcoming Events</h2><Link to="/events">View all →</Link></div><div className="event-list">{upcoming.slice(0,5).map(e=><Link to={`/events/${e.id}`} className="event-row" key={e.id}><div className="event-date"><strong>{new Date(e.start_time).getDate()}</strong><span>{new Date(e.start_time).toLocaleString('en',{month:'short'})}</span></div><div><strong>{e.title}</strong><small>{new Date(e.start_time).toLocaleString()} · {e.is_free?'Free':`₹${e.registration_fee}`}</small></div><span className={`status-pill ${regEventIds.has(e.id)?'success':''}`}>{regEventIds.has(e.id)?'Registered':'View'}</span></Link>)}{upcoming.length===0&&<p className="empty-state">No upcoming events yet.</p>}</div></div><div className="panel ai-panel"><span className="icon-bubble">✦</span><h2>Let AI help you</h2><p>Find events, plan a venue, check policies or create an event with natural language.</p><Link className="primary-link" to="/agent">Open Agent →</Link>{isEventManager&&<Link className="secondary-link" to="/manager">Event Manager workspace →</Link>}</div></section></main></Layout>}
function Stat({label,value,icon}){return <div className="stat-card"><span className="stat-icon">{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>}
