from fastapi import APIRouter, Depends
from pydantic import BaseModel
from langchain_core.messages import HumanMessage, AIMessage

from app.agent.graph import build_agent
from app.api.deps import get_current_user
from app.models.user import User

router = APIRouter()


class AgentRequest(BaseModel):
    message: str
    user_id: str | None = None
    session_id: str | None = None


class AgentResponse(BaseModel):
    response: str


def extract_text(content) -> str:
    """Extract readable text from LangChain message content."""

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):
        parts = []

        for item in content:
            if isinstance(item, str):
                parts.append(item)

            elif isinstance(item, dict):
                text = item.get("text")

                if text:
                    parts.append(str(text))

        return "\n".join(parts).strip()

    if isinstance(content, dict):
        text = content.get("text")

        if text:
            return str(text).strip()

    return ""


@router.post("/chat", response_model=AgentResponse)
def chat_with_agent(
    request: AgentRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Process an authenticated user's request through the event-management AI agent.
    """

    user_agent = build_agent(
        user_id=str(current_user.id),
        role=current_user.role,
    )

    result = user_agent.invoke(
        {"messages": [HumanMessage(content=f"User request: {request.message}")]}
    )

    messages = result.get("messages", [])

    # Only return text generated by the AI.
    # Never return the HumanMessage as a fallback.
    for message in reversed(messages):

        if isinstance(message, AIMessage):
            text = extract_text(message.content)

            if text:
                return AgentResponse(response=text)

    # If the agent completed a tool operation but did not
    # generate a readable final AI response.
    return AgentResponse(
        response=(
            "The operation was processed, but the AI did not "
            "return a readable final response."
        )
    )
